prepare-env:
    curl --proto '=https' --tlsv1.2 -fL -o ocb https://github.com/open-telemetry/opentelemetry-collector-releases/releases/download/cmd%2Fbuilder%2Fv0.158.0/ocb_0.158.0_darwin_arm64
    chmod +x ocb

generate:
    nix shell nixpkgs#go
    ./ocb --skip-compilation --config builder-config.yaml
