#!/bin/sh
#
# Starts otelarmv7col
#
NAME=otelarmv7col
DAEMON=/usr/bin/$NAME
PIDFILE="/var/run/$NAME.pid"
CONFIG=/etc/otelcol/config.yaml

start() {
	printf "Starting $NAME: "
	DEVICE_MAC="$(cat /sys/class/net/eth0/address)"
	export DEVICE_MAC
	start-stop-daemon -S -q -b -m -p "$PIDFILE" -x "$DAEMON" -- --config "$CONFIG"
	echo "OK"
}

stop() {
	printf "Stopping $NAME: "
	start-stop-daemon -K -q -p "$PIDFILE"
	echo "OK"
}

restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
