#!/usr/bin/env python3
"""Generate the checked-in U-Boot fragment; --check detects drift in CI/tests."""
import json
from pathlib import Path
import sys
board = Path(__file__).resolve().parent
command = ' '.join(line.strip() for line in (board / 'boot-ab.cmd').read_text().splitlines()
                   if line.strip() and not line.lstrip().startswith('#'))
fragment = '''# Generated by generate-boot-config.py from boot-ab.cmd.
# Two 64 KiB copies, outside GPT partitions and SPL/U-Boot.
# CONFIG_ENV_IS_IN_FAT is not set
# CONFIG_ENV_IS_IN_SPI_FLASH is not set
# CONFIG_ENV_IS_NOWHERE is not set
CONFIG_ENV_IS_IN_MMC=y
CONFIG_SYS_MMC_ENV_DEV=0
CONFIG_SYS_MMC_ENV_PART=0
CONFIG_ENV_SIZE=0x10000
CONFIG_ENV_OFFSET=0x120000
CONFIG_ENV_OFFSET_REDUND=0x130000
CONFIG_SYS_REDUNDAND_ENVIRONMENT=y
CONFIG_CMD_SAVEENV=y
CONFIG_CMD_EXT4=y
CONFIG_CMD_SETEXPR=y
CONFIG_WATCHDOG_AUTOSTART=y
CONFIG_WATCHDOG_TIMEOUT_MSECS=16000
CONFIG_USE_BOOTCOMMAND=y
CONFIG_BOOTCOMMAND=''' + json.dumps(command) + '\n'
path = board / 'uboot-ota.config'
if '--check' in sys.argv:
    if path.read_text() != fragment:
        sys.exit('uboot-ota.config is stale: run generate-boot-config.py')
else:
    path.write_text(fragment)
